import type { Playlist, SettingsState, Track } from "./types";

const audio = (song: number) => `https://www.soundhelix.com/examples/mp3/SoundHelix-Song-${song}.mp3`;

export const seedTracks: Track[] = [
  {
    id: "glimmer",
    title: "Glimmer",
    artist: "London Grammar",
    album: "Velvet Signal",
    duration: 217,
    source: "spotify",
    audioUrl: audio(1),
    spotifyUrl: "https://open.spotify.com/search/Glimmer%20London%20Grammar",
    youtubeUrl: "https://music.youtube.com/search?q=Glimmer+London+Grammar",
    cover: "linear-gradient(135deg, #112d1c 0%, #38e36a 45%, #07110d 100%)",
    accent: "#65ff75",
    bpm: 92,
    mood: "Night drive",
    lyrics: [
      "Green light on the window",
      "Your voice turns into rain",
      "Every little echo",
      "Finds the pulse again",
      "I keep the signal glowing",
      "Till the silence bends",
    ],
  },
  {
    id: "entitlement",
    title: "Entitlement",
    artist: "Beach Bunny",
    album: "Soft Static",
    duration: 169,
    source: "youtube",
    audioUrl: audio(2),
    spotifyUrl: "https://open.spotify.com/search/Entitlement%20Beach%20Bunny",
    youtubeUrl: "https://music.youtube.com/search?q=Entitlement+Beach+Bunny",
    cover: "linear-gradient(135deg, #ffb44c 0%, #ff5a4f 52%, #2b1111 100%)",
    accent: "#ff684f",
    bpm: 146,
    mood: "Indie spark",
    lyrics: [
      "I wrote your name in marker",
      "On the back of summer air",
      "Every chord gets brighter",
      "When you pretend you care",
      "I am done with waiting",
      "For a sign that is not there",
    ],
  },
  {
    id: "nights",
    title: "Nights",
    artist: "Frank Ocean",
    album: "Late Avenue",
    duration: 307,
    source: "spotify",
    audioUrl: audio(3),
    spotifyUrl: "https://open.spotify.com/search/Nights%20Frank%20Ocean",
    youtubeUrl: "https://music.youtube.com/search?q=Nights+Frank+Ocean",
    cover: "linear-gradient(135deg, #f4f4f4 0%, #aeb6c2 44%, #050509 100%)",
    accent: "#d9dee7",
    bpm: 88,
    mood: "After hours",
    lyrics: [
      "City glass is folding",
      "Headlights count the years",
      "All the things we carried",
      "Sound different from here",
      "Let the second half start",
      "With nothing left to fear",
    ],
  },
  {
    id: "one-more-time",
    title: "One More Time",
    artist: "Daft Punk",
    album: "Chrome Party",
    duration: 320,
    source: "youtube",
    audioUrl: audio(4),
    spotifyUrl: "https://open.spotify.com/search/One%20More%20Time%20Daft%20Punk",
    youtubeUrl: "https://music.youtube.com/search?q=One+More+Time+Daft+Punk",
    cover: "linear-gradient(135deg, #101729 0%, #4a7dff 38%, #ffd84a 70%, #090b11 100%)",
    accent: "#70a6ff",
    bpm: 123,
    mood: "Dance floor",
    lyrics: [
      "Raise the roof in color",
      "Let the speakers climb",
      "Every hand remembers",
      "How to find the time",
      "Again the room is moving",
      "Again the stars align",
    ],
  },
  {
    id: "it-gets-better",
    title: "It Gets Better",
    artist: "Rex Orange County",
    album: "Small Windows",
    duration: 215,
    source: "spotify",
    audioUrl: audio(5),
    spotifyUrl: "https://open.spotify.com/search/It%20Gets%20Better%20Rex%20Orange%20County",
    youtubeUrl: "https://music.youtube.com/search?q=It+Gets+Better+Rex+Orange+County",
    cover: "linear-gradient(135deg, #eef4e8 0%, #6ad3aa 50%, #1a3026 100%)",
    accent: "#8dffce",
    bpm: 104,
    mood: "Warm reset",
    lyrics: [
      "Open blinds at sunrise",
      "Dust is turning gold",
      "Everything gets lighter",
      "When the day unfolds",
      "I know the road is longer",
      "But the wheel still holds",
    ],
  },
  {
    id: "about-you",
    title: "About You",
    artist: "The 1975",
    album: "Mirror Talk",
    duration: 252,
    source: "spotify",
    audioUrl: audio(6),
    spotifyUrl: "https://open.spotify.com/search/About%20You%20The%201975",
    youtubeUrl: "https://music.youtube.com/search?q=About+You+The+1975",
    cover: "linear-gradient(135deg, #d9dad9 0%, #88919a 45%, #171a20 100%)",
    accent: "#d1d9e8",
    bpm: 72,
    mood: "Cinema haze",
    lyrics: [
      "The room keeps your outline",
      "Even after rain",
      "Every frame is drifting",
      "Back into your name",
      "I try to leave the picture",
      "But the light remains",
    ],
  },
  {
    id: "sunset-lover",
    title: "Sunset Lover",
    artist: "Petit Biscuit",
    album: "Blue Signal",
    duration: 237,
    source: "youtube",
    audioUrl: audio(7),
    spotifyUrl: "https://open.spotify.com/search/Sunset%20Lover%20Petit%20Biscuit",
    youtubeUrl: "https://music.youtube.com/search?q=Sunset+Lover+Petit+Biscuit",
    cover: "linear-gradient(135deg, #ff8a3d 0%, #224d83 44%, #060a12 100%)",
    accent: "#ff9b55",
    bpm: 98,
    mood: "Coastal",
    lyrics: [
      "Salt air through the speakers",
      "Orange on the tide",
      "We were made of distance",
      "And a softer kind of light",
      "Hold the last reflection",
      "Till the stars arrive",
    ],
  },
  {
    id: "see-you-again",
    title: "See You Again",
    artist: "Tyler, The Creator",
    album: "Pastel Radio",
    duration: 180,
    source: "spotify",
    audioUrl: audio(8),
    spotifyUrl: "https://open.spotify.com/search/See%20You%20Again%20Tyler%20The%20Creator",
    youtubeUrl: "https://music.youtube.com/search?q=See+You+Again+Tyler+The+Creator",
    cover: "linear-gradient(135deg, #f2d6a2 0%, #fb7171 46%, #2a172a 100%)",
    accent: "#ff9f8a",
    bpm: 79,
    mood: "Dream pop",
    lyrics: [
      "I kept a postcard folded",
      "Where the chorus used to be",
      "Every color wandered",
      "Into something sweet",
      "Maybe in the morning",
      "You will visit me",
    ],
  },
  {
    id: "less-i-know",
    title: "The Less I Know The Better",
    artist: "Tame Impala",
    album: "Neon Bloom",
    duration: 216,
    source: "youtube",
    audioUrl: audio(9),
    spotifyUrl: "https://open.spotify.com/search/The%20Less%20I%20Know%20The%20Better%20Tame%20Impala",
    youtubeUrl: "https://music.youtube.com/search?q=The+Less+I+Know+The+Better+Tame+Impala",
    cover: "linear-gradient(135deg, #2b1b56 0%, #e84d65 52%, #ffcb52 100%)",
    accent: "#ffcb52",
    bpm: 117,
    mood: "Psychedelic",
    lyrics: [
      "Bassline in the hallway",
      "Walls begin to bend",
      "I can hear the answer",
      "Before the question ends",
      "Maybe knowing less now",
      "Is the way to mend",
    ],
  },
  {
    id: "eventually",
    title: "Eventually",
    artist: "Tame Impala",
    album: "Neon Bloom",
    duration: 319,
    source: "spotify",
    audioUrl: audio(10),
    spotifyUrl: "https://open.spotify.com/search/Eventually%20Tame%20Impala",
    youtubeUrl: "https://music.youtube.com/search?q=Eventually+Tame+Impala",
    cover: "linear-gradient(135deg, #321313 0%, #ff6048 45%, #0b090a 100%)",
    accent: "#ff735f",
    bpm: 78,
    mood: "Slow burn",
    lyrics: [
      "There is a fire behind us",
      "But the smoke has learned to fade",
      "Every quiet ending",
      "Makes a little space",
      "Eventually the weather",
      "Will remember grace",
    ],
  },
];

export const seedPlaylists: Playlist[] = [
  {
    id: "discover-weekly",
    title: "Discover Weekly",
    description: "Spotify source, cached for fast Windows startup",
    source: "spotify",
    tracks: ["glimmer", "it-gets-better", "see-you-again", "eventually"],
    cover: "linear-gradient(135deg, #07110d, #46ff78 52%, #0a0d14)",
  },
  {
    id: "youtube-mix",
    title: "YouTube Mix",
    description: "Matched playback candidates",
    source: "youtube",
    tracks: ["entitlement", "sunset-lover", "one-more-time", "less-i-know"],
    cover: "linear-gradient(135deg, #270707, #ff4f4f 50%, #090b11)",
  },
  {
    id: "chill-focus",
    title: "Chill Focus",
    description: "Low-energy queue with lyrics",
    source: "spotify",
    tracks: ["nights", "about-you", "eventually", "glimmer"],
    cover: "linear-gradient(135deg, #05111d, #168dff 45%, #04070d)",
  },
  {
    id: "workout-pulse",
    title: "Workout Pulse",
    description: "Smart queue generated from BPM",
    source: "spotify",
    tracks: ["one-more-time", "entitlement", "less-i-know", "sunset-lover"],
    cover: "linear-gradient(135deg, #102113, #b8ff1b 45%, #080b09)",
  },
  {
    id: "local-imports",
    title: "Local imports",
    description: "Drop MP3, FLAC, WAV, or M4A files",
    source: "local",
    tracks: [],
    cover: "linear-gradient(135deg, #15151b, #45d5ff 46%, #081017)",
  },
];

export const defaultSettings: SettingsState = {
  spotifyConnected: false,
  spotifyClientId: "",
  spotifyClientSecret: "",
  spotifyAccessToken: "",
  youtubeApiKey: "",
  youtubeAccessToken: "",
  youtubeEndpoint: "https://music.youtube.com",
  spotifyForHome: true,
  spotifyForSearch: true,
  youtubeForSearch: true,
  discordPresence: true,
  discordClientId: "",
  onboardingComplete: false,
  autoLoadLibrary: true,
  reduceMotion: false,
  normalizeAudio: true,
};
